### ISSUE TITLE
Clicking items

### ISSUE THREAD

**Issue by tinoper** [Wrdlbrnft/Searchable-RecyclerView-Demo#14]
Hi, I'm researching your Searchable-RecyclerView but I would like make clickable items (filtered o not filtered). So I implement View.OnClickListener in ExampleAdapter but I'm not sure if it is the best approach to your project. If you have to add, this feature what do you think is the right way make it possible?

Regards,

**Comment by abhijith-gururaj** [comment]
You can check my fork for item click listener functionality. For some reason, the author did not accept my pr. Here's the link: https://github.com/abhijith-gururaj/Searchable-RecyclerView-Demo

**Comment by tinoper** [comment]
Hi abhijith-gururaj, I'm checking out your fork about this rep. Indeed, I'm testing your version but after filter the original list if you click on any result the toast returns the value with position at original list. I mean, the second element filtered isn't the second element in the list but it shows anyways. Maybe it's something you are working on. Regards,

**Comment by Wrdlbrnft** [comment]
I am not sure I will add this feature since it essentially has nothing to do with the demo and I want to keep the code as simple as possible. @abhijith-gururaj  I didn't accept your pull request 1) for the very reason I just stated and 2) because your fork is more than 20 commits behind and based on an ancient version of this project! @tinoper  You shouldn't use the fork of @abhijith-gururaj since it is horribly outdated. The current implementation of the project is a lot better and you should use that as your template. If you really want I can maybe add a basic click listener for the items...

**Comment by tinoper** [comment]
Hi Xaver, I understand that keep it simple is the best. I'm just researching to improve what I'm using today. Indeed, you are using databinding and I like very much the rest of the code. If you like feel free to add this feature or give some approach about how to do it, as you wish. Nice work again. Regards,

**Comment by Wrdlbrnft** [comment]
I just added a basic click listener using data binding. When ever you click on a model now a Snackbar is shown at the bottom of the screen.
